customSyntax: '@stylelint/postcss-css-in-js'
plugins:
  - stylelint-config-rational-order/plugin
  - stylelint-order
  - '@stylistic/stylelint-plugin'
extends:
  - stylelint-config-recommended
  - '@stylistic/stylelint-config'
ignoreFiles:
  - 'node_modules/**/*'
  - 'dist/**/*'
  - '**/*.d.ts'
rules:
  order/properties-order:
    - []
    - unspecified: bottom
      emptyLineMinimumPropertyThreshold: 4

  plugin/rational-order:
    - true
    - empty-line-between-groups: threshold
      empty-line-property-threshold: 3
      empty-lines-within-groups: false
      empty-line-before-unspecified: always
      unspecified: bottomAlphabetical

  '@stylistic/color-hex-case': upper
  '@stylistic/indentation': 2
  '@stylistic/selector-max-empty-lines': 2
  '@stylistic/string-quotes': single
  '@stylistic/no-empty-first-line': null
  '@stylistic/no-eol-whitespace': null
