extends:
  - stylelint-config-standard
  - stylelint-config-styled-components
plugins:
  - stylelint-order
processors:
  - stylelint-processor-styled-components
rules:
  order/properties-alphabetical-order: true
  color-hex-case: upper
  indentation: 2
