extends:
  - stylelint-config-standard
  - stylelint-config-styled-components
plugins:
  - stylelint-order
  - stylelint-config-rational-order/plugin
rules:
  order/properties-order: []

  plugin/rational-order:
    - true
    - empty-line-between-groups: true

  block-no-empty: null
  color-hex-case: upper
  indentation: 2
