yarnPath: /Users/daniel/Repos/Personal/daniel.sh/.yarn/releases/yarn-berry.js
packageExtensions:
  carbon-components-react@*:
    dependencies:
      prop-types: '*'
  gatsby-plugin-graphql-codegen@*:
    peerDependencies:
      graphql: '*'
  gatsby-remark-embed-snippet@*:
    dependencies:
      unist-util-visit: '*'
  postcss-syntax@*:
    dependencies:
      postcss-html: '>= 0.36.0'
      postcss-jsx: '>= 0.36.0'
      postcss-less: ^3.1.0
      postcss-markdown: '>= 0.36.0'
      postcss-scss: ^2.0.0
  scss-to-json@*:
    dependencies:
      node-sass: ^4.13.1
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"
