checksumBehavior: update

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${FONTAWESOME_NPM_TOKEN:-}"
    npmRegistryServer: "https://npm.fontawesome.com"
  gsap:
    npmAlwaysAuth: true
    npmAuthToken: "${GSAP_NPM_TOKEN:-}"
    npmRegistryServer: "https://npm.greensock.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
