services:
  app:
    build:
      context: .
      secrets:
        - source: environment
          mode: 0440
    environment:
      - VIRTUAL_HOST=danielsh.here
    expose:
      - '3000'
    networks:
      - default
      - nginx-proxy
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules

networks:
  default:
  nginx-proxy:
    external: true
    name: nginx-proxy

secrets:
  environment:
    file: .env

volumes:
  node_modules:
