services:
  app:
    build:
      context: .
      secrets:
        - source: environment
          mode: 0440
    environment:
      - VIRTUAL_HOST=danielsh.here
    expose:
      - '3000'
    networks:
      - default
      - nginx-proxy
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
          ignore:
            - node_modules/
        - path: ./public
          target: /app/public
          action: sync
          ignore:
            - node_modules/
        - action: rebuild
          path: yarn.lock

networks:
  default:
  nginx-proxy:
    external: true
    name: nginx-proxy

secrets:
  environment:
    file: .env
