import { defineConfig } from "oxlint";

export default defineConfig({
    plugins: [],
    jsPlugins: ["@stylistic/eslint-plugin"],
    categories: {
        correctness: "off",
    },
    env: {
        builtin: true,
    },
    rules: {
        "constructor-super": "error",
        "for-direction": "error",
        "getter-return": "error",
        "no-async-promise-executor": "error",
        "no-case-declarations": "error",
        "no-class-assign": "error",
        "no-compare-neg-zero": "error",
        "no-cond-assign": "error",
        "no-const-assign": "error",
        "no-constant-binary-expression": "error",
        "no-constant-condition": "error",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-delete-var": "error",
        "no-dupe-class-members": "error",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-empty": "error",
        "no-empty-character-class": "error",
        "no-empty-pattern": "error",
        "no-empty-static-block": "error",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "error",
        "no-fallthrough": "error",
        "no-func-assign": "error",
        "no-global-assign": "error",
        "no-import-assign": "error",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-loss-of-precision": "error",
        "no-misleading-character-class": "error",
        "no-new-native-nonconstructor": "error",
        "no-nonoctal-decimal-escape": "error",
        "no-obj-calls": "error",
        "no-prototype-builtins": "error",
        "no-redeclare": "error",
        "no-regex-spaces": "error",
        "no-self-assign": "error",
        "no-setter-return": "error",
        "no-shadow-restricted-names": "error",
        "no-sparse-arrays": "error",
        "no-this-before-super": "error",
        "no-unassigned-vars": "error",
        "no-undef": "error",
        "no-unexpected-multiline": "error",
        "no-unreachable": "error",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "error",
        "no-unsafe-optional-chaining": "error",
        "no-unused-labels": "error",
        "no-unused-private-class-members": "error",
        "no-unused-vars": "error",
        "no-useless-assignment": "error",
        "no-useless-backreference": "error",
        "no-useless-catch": "error",
        "no-useless-escape": "error",
        "no-with": "error",
        "preserve-caught-error": "error",
        "require-yield": "error",
        "use-isnan": "error",
        "valid-typeof": "error",

        "@stylistic/array-bracket-spacing": ["error", "never"],
        "@stylistic/arrow-parens": [
            "warn",
            "as-needed",
            {
                requireForBlockBody: false,
            },
        ],
        "@stylistic/arrow-spacing": [
            "error",
            {
                after: true,
                before: true,
            },
        ],
        "@stylistic/block-spacing": ["warn", "never"],
        "@stylistic/brace-style": [
            "warn",
            "1tbs",
            {
                allowSingleLine: true,
            },
        ],
        "@stylistic/comma-dangle": ["warn", "always-multiline"],
        "@stylistic/comma-spacing": [
            "warn",
            {
                after: true,
                before: false,
            },
        ],
        "@stylistic/comma-style": ["error", "last"],
        "@stylistic/computed-property-spacing": [
            "error",
            "never",
            {
                enforceForClassMembers: true,
            },
        ],
        "@stylistic/dot-location": ["error", "property"],
        "@stylistic/eol-last": "warn",
        "@stylistic/generator-star-spacing": [
            "error",
            {
                after: true,
                before: false,
            },
        ],
        "@stylistic/indent": ["warn", 4],
        "@stylistic/indent-binary-ops": ["error", 2],
        "@stylistic/key-spacing": [
            "error",
            {
                afterColon: true,
                beforeColon: false,
            },
        ],
        "@stylistic/keyword-spacing": [
            "error",
            {
                after: true,
                before: true,
            },
        ],
        "@stylistic/lines-between-class-members": [
            "error",
            "always",
            {
                exceptAfterSingleLine: true,
            },
        ],
        "@stylistic/max-statements-per-line": [
            "error",
            {
                max: 1,
            },
        ],
        "@stylistic/member-delimiter-style": [
            "warn",
            {
                multiline: {
                    delimiter: "semi",
                    requireLast: true,
                },
                singleline: {
                    delimiter: "semi",
                    requireLast: false,
                },
            },
        ],
        "@stylistic/multiline-ternary": ["error", "always-multiline"],
        "@stylistic/new-parens": "error",
        "@stylistic/no-extra-parens": ["error", "functions"],
        "@stylistic/no-floating-decimal": "error",
        "@stylistic/no-mixed-operators": [
            "error",
            {
                allowSamePrecedence: true,
                groups: [
                    ["==", "!=", "===", "!==", ">", ">=", "<", "<="],
                    ["&&", "||"],
                    ["in", "instanceof"],
                ],
            },
        ],
        "@stylistic/no-mixed-spaces-and-tabs": "error",
        "@stylistic/no-multi-spaces": "error",
        "@stylistic/no-multiple-empty-lines": [
            "warn",
            {
                max: 2,
                maxBOF: 0,
                maxEOF: 1,
            },
        ],
        "@stylistic/no-tabs": "error",
        "@stylistic/no-trailing-spaces": "warn",
        "@stylistic/no-whitespace-before-property": "error",
        "@stylistic/object-curly-spacing": ["warn", "always"],
        "@stylistic/operator-linebreak": "warn",
        "@stylistic/padded-blocks": [
            "error",
            {
                blocks: "never",
                classes: "never",
                switches: "never",
            },
        ],
        "@stylistic/quote-props": ["warn", "consistent-as-needed"],
        "@stylistic/quotes": [
            "warn",
            "double",
            {
                allowTemplateLiterals: "always",
                avoidEscape: true,
            },
        ],
        "@stylistic/rest-spread-spacing": ["error", "never"],
        "@stylistic/semi": [
            "warn",
            "always",
            {
                omitLastInOneLineBlock: true,
                omitLastInOneLineClassBody: true,
            },
        ],
        "@stylistic/semi-spacing": [
            "error",
            {
                after: true,
                before: false,
            },
        ],
        "@stylistic/space-before-blocks": ["error", "always"],
        "@stylistic/space-before-function-paren": "warn",
        "@stylistic/space-in-parens": ["error", "never"],
        "@stylistic/space-infix-ops": "error",
        "@stylistic/space-unary-ops": [
            "error",
            {
                nonwords: false,
                words: true,
            },
        ],
        "@stylistic/spaced-comment": [
            "error",
            "always",
            {
                block: {
                    balanced: true,
                    exceptions: ["*"],
                    markers: ["!"],
                },
                line: {
                    exceptions: ["/", "#"],
                    markers: ["/"],
                },
            },
        ],
        "@stylistic/template-curly-spacing": ["warn", "always"],
        "@stylistic/template-tag-spacing": ["error", "never"],
        "@stylistic/type-annotation-spacing": ["error", {}],
        "@stylistic/type-generic-spacing": "error",
        "@stylistic/type-named-tuple-spacing": "error",
        "@stylistic/wrap-iife": [
            "error",
            "any",
            {
                functionPrototypeMethods: true,
            },
        ],
        "@stylistic/yield-star-spacing": [
            "error",
            {
                after: true,
                before: false,
            },
        ],

        "@stylistic/jsx-closing-bracket-location": ["warn", "after-props"],
        "@stylistic/jsx-closing-tag-location": "error",
        "@stylistic/jsx-curly-brace-presence": [
            "error",
            {
                propElementValues: "always",
            },
        ],
        "@stylistic/jsx-curly-newline": ["warn", "consistent"],
        "@stylistic/jsx-curly-spacing": [
            "warn",
            {
                attributes: { when: "always" },
                children: { when: "always" },
                spacing: { objectLiterals: "never" },
                when: "always",
            },
        ],
        "@stylistic/jsx-equals-spacing": "error",
        "@stylistic/jsx-first-prop-new-line": "error",
        "@stylistic/jsx-function-call-newline": ["error", "multiline"],
        "@stylistic/jsx-indent-props": ["warn", 4],
        "@stylistic/jsx-max-props-per-line": [
            "error",
            {
                maximum: 1,
                when: "multiline",
            },
        ],
        "@stylistic/jsx-one-expression-per-line": [
            "warn",
            {
                allow: "single-line",
            },
        ],
        "@stylistic/jsx-quotes": ["warn", "prefer-double"],
        "@stylistic/jsx-tag-spacing": [
            "warn",
            {
                afterOpening: "never",
                beforeClosing: "never",
                beforeSelfClosing: "always",
                closingSlash: "never",
            },
        ],
        "@stylistic/jsx-wrap-multilines": [
            "error",
            {
                arrow: "parens-new-line",
                assignment: "parens-new-line",
                condition: "parens-new-line",
                declaration: "parens-new-line",
                logical: "parens-new-line",
                prop: "parens-new-line",
                propertyValue: "parens-new-line",
                return: "parens-new-line",
            },
        ],
    },
    overrides: [
        {
            files: ["**/*.{js,jsx,mjs,cjs,ts,tsx}"],
            rules: {
                "react/react-in-jsx-scope": "off",
                "jsx-a11y/alt-text": "error",
                "jsx-a11y/anchor-ambiguous-text": "off",
                "jsx-a11y/anchor-has-content": "error",
                "jsx-a11y/anchor-is-valid": "error",
                "jsx-a11y/aria-activedescendant-has-tabindex": "error",
                "jsx-a11y/aria-props": "error",
                "jsx-a11y/aria-proptypes": "error",
                "jsx-a11y/aria-role": "error",
                "jsx-a11y/aria-unsupported-elements": "error",
                "jsx-a11y/autocomplete-valid": "error",
                "jsx-a11y/click-events-have-key-events": "error",
                "jsx-a11y/control-has-associated-label": [
                    "off",
                    {
                        ignoreElements: [
                            "audio",
                            "canvas",
                            "embed",
                            "input",
                            "textarea",
                            "tr",
                            "video",
                        ],
                        ignoreRoles: [
                            "grid",
                            "listbox",
                            "menu",
                            "menubar",
                            "radiogroup",
                            "row",
                            "tablist",
                            "toolbar",
                            "tree",
                            "treegrid",
                        ],
                        // NOTE: `includeRoles` is an eslint-plugin-jsx-a11y option that
                        // oxlint's native implementation doesn't support.
                    },
                ],
                "jsx-a11y/heading-has-content": "error",
                "jsx-a11y/html-has-lang": "error",
                "jsx-a11y/iframe-has-title": "error",
                "jsx-a11y/img-redundant-alt": "error",
                "jsx-a11y/interactive-supports-focus": [
                    "error",
                    {
                        tabbable: [
                            "button",
                            "checkbox",
                            "link",
                            "searchbox",
                            "spinbutton",
                            "switch",
                            "textbox",
                        ],
                    },
                ],
                "jsx-a11y/label-has-associated-control": "error",
                "jsx-a11y/media-has-caption": "error",
                "jsx-a11y/mouse-events-have-key-events": "error",
                "jsx-a11y/no-access-key": "error",
                "jsx-a11y/no-autofocus": "error",
                "jsx-a11y/no-distracting-elements": "error",
                "jsx-a11y/no-interactive-element-to-noninteractive-role": [
                    "error",
                    {
                        tr: ["none", "presentation"],
                        canvas: ["img"],
                    },
                ],
                "jsx-a11y/no-noninteractive-element-interactions": [
                    "error",
                    {
                        handlers: [
                            "onClick",
                            "onError",
                            "onLoad",
                            "onMouseDown",
                            "onMouseUp",
                            "onKeyPress",
                            "onKeyDown",
                            "onKeyUp",
                        ],
                        alert: ["onKeyUp", "onKeyDown", "onKeyPress"],
                        body: ["onError", "onLoad"],
                        dialog: ["onKeyUp", "onKeyDown", "onKeyPress"],
                        iframe: ["onError", "onLoad"],
                        img: ["onError", "onLoad"],
                    },
                ],
                "jsx-a11y/no-noninteractive-element-to-interactive-role": [
                    "error",
                    {
                        ul: [
                            "listbox",
                            "menu",
                            "menubar",
                            "radiogroup",
                            "tablist",
                            "tree",
                            "treegrid",
                        ],
                        ol: [
                            "listbox",
                            "menu",
                            "menubar",
                            "radiogroup",
                            "tablist",
                            "tree",
                            "treegrid",
                        ],
                        li: [
                            "menuitem",
                            "menuitemradio",
                            "menuitemcheckbox",
                            "option",
                            "row",
                            "tab",
                            "treeitem",
                        ],
                        table: ["grid"],
                        td: ["gridcell"],
                        fieldset: ["radiogroup", "presentation"],
                    },
                ],
                "jsx-a11y/no-noninteractive-tabindex": [
                    "error",
                    {
                        tags: [],
                        roles: ["tabpanel"],
                        allowExpressionValues: true,
                    },
                ],
                "jsx-a11y/no-redundant-roles": "error",
                "jsx-a11y/no-static-element-interactions": [
                    "error",
                    {
                        allowExpressionValues: true,
                        handlers: [
                            "onClick",
                            "onMouseDown",
                            "onMouseUp",
                            "onKeyPress",
                            "onKeyDown",
                            "onKeyUp",
                        ],
                    },
                ],
                "jsx-a11y/role-has-required-aria-props": "error",
                "jsx-a11y/role-supports-aria-props": "error",
                "jsx-a11y/scope": "error",
                "jsx-a11y/tabindex-no-positive": "error",
                "react/exhaustive-deps": "warn",
            },
            globals: {
                AsyncDisposableStack: "readonly",
                DisposableStack: "readonly",
                SuppressedError: "readonly",
            },
            env: {
                browser: true,
                es2026: true,
                worker: true,
            },
            plugins: ["react", "jsx-a11y"],
        },
    ],
});
